#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
#=================================================================#
#   Description:           Caddy  Server                          #
#   System Required:       Centos 8 x86_64                        #
#   Thanks:                Myself                                 #
#=================================================================#

cd /usr/local/bin

wget --no-check-certificate https://github.com/caddyserver/caddy/releases/download/v1.0.3/caddy_v1.0.3_linux_amd64.tar.gz  

tar -xzf caddy*.tar.gz caddy

echo "www.greggho.ml{
 gzip
 tls greggho.contact@gmail.com
 proxy / 127.0.0.1:10001 {
 websocket
 }
}" > /usr/local/bin/Caddyfile

# 开机自启
cat > /etc/systemd/system/Caddy.service<<-EOF
[Unit]
Description=Caddy Server

[Service]
ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp
Restart=always
[Install]
WantedBy=multi-user.target
EOF

systemctl enable Caddy.service

#启动
systemctl start Caddy.service

